### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by rujanr** [zecure/shadowd#36] opened 2020-05-04 22:33 UTC
Hello, 
What is the impact of setting/not setting the SSL variable in in the .ini configuration file? 
Is it necessary only for the secure connection to the web ui?

**Comment by zit-hb** [comment] 2020-05-05 06:58
It depends on your setup but probably you do not have to enable SSL. It is used for transmitting the data from the connector to shadowd. So for example if you run shadowd on the same server as the web app that you want to protect there is no point in enabling SSL. I would only recommend to use it if the connection between the connector and shadowd is not trusted.

**Comment by rujanr** [comment] 2020-05-05 14:27
Great, thank you for the answer! 
3 more questions, although not in the correct thread:
- where to check the status if the traffic is filtered by shadowd?
- I understand that the blacklist is already a default blacklist configured - as descibed here- https://shadowd.zecure.org/documentation/blacklist/ , where the blacklist can be extended with additional rules; is there a possibility of conflicting rules and if yes , how to check?
- what is the difference compared to mod_security? any future plans for owasp rules integration ?

**Comment by zit-hb** [comment] 2020-05-05 15:16
You are welcome!

1. I would start with a `phpinfo();` (in case you are using it for PHP). This way you can see if `auto_prepend_file` is set correctly. After than I would enable the learning mode for the profile through the UI, then every request should be logged, so easy to verify it is working.
2. It was a design decision of mine not to allow this. Basically I wanted to create a WAF that you can set up once and that will still work fine 10 years later if you have no touched it (meaning, still able to detect attacks). The existing blacklist filters reflect this. If you have good ideas for new blacklist filters I am very happy about suggestions though: https://shadowd.zecure.org/documentation/blacklist/
3. Shadow Daemon intercepts the requests at a different level than mod_security. Let's say you have an `index.php` and a client requests it through an Apache web server. mod_security would parse the request before it is send to PHP and try to detect attack patterns. Shadow Daemon would process the request after it is processed by PHP but before the code of `index.php` is executed. This means Shadow Daemon sees exactly the same data that the script sees while mod_security might have misunderstood the request (there are WAF bypasses that use this approach). The blacklist approach of mod_security and Shadow Daemon is quite similar (and they partially share some rules here, though I haven't looked at what has changed in the last years at mod_security). As far as I am aware mod_security does not have a whitelist protection though. But of course the approach of mod_security also allows to do things that you can't do with the Shadow Daemon approach. It is also perfectly fine to use both at the same time, they won't interfere with each other.

**Comment by rujanr** [comment] 2020-05-05 18:00
Hi, thank you again for the response. Using shadowd with PHP Connector with Apache on Ubuntu 16.04, for Wordpress and Laravel.
Used both methods (global php configurations / specific vhost config for Apache) to install the PHP conenctor. Auto prepend variable is shown in php.info .  Shadowd is in learning mode . Still no logging shown in the UI . 
However the system seems to be filtering request since changes in the connectors.ini (such as setting a random SSL variable)  impact the functioning of the web service (service not functioning).
Any hints?

**Comment by zit-hb** [comment] 2020-05-05 20:09
Sorry, I can't reproduce it. I just set up a fresh Ubuntu 16.04.4 with Apache and PHP and it works without any problems. Can you share some more information, i.e. a bit more details how you installed it?

**Comment by rujanr** [comment] 2020-05-05 22:10
Hello. I installed shadowd on docker, on a Ubuntu 16.04 box, as described  above, according to the instructions on the site. There was a particularity of the installation. 
UFW Firewall opened only ports for https and ssh. However, Docker bypasses the UFW rules, leaving all ports towards Docker open . Therefore in order to make the firewall policies effective on Docker, I applied the solution described here: https://github.com/chaifeng/ufw-docker , using ufw forward.
Might there be an influence because of this particular UFW settings?

**Comment by zit-hb** [comment] 2020-05-06 06:55
Hey, it is certainly possible that it is caused by that, I am not sure how it would behave. I am doing the following myself: edit the docker-compose.yml and bind the port to localhost only. This way no one from the outside can access it. You can then use your normal web server, add a vhost, and use that as a reverse proxy.

**Comment by rujanr** [comment] 2020-05-08 00:36
Hi, 
Unfortunately, I doubt it is the firewall. Just did a fresh install of the system and was able to reproduce the problem.
I will describe  in detail:

Both machines run Ubuntu 16.04 . 
Webserver: Apache. 
Shadowd Installation: on Docker
Connector: PHP- (in both options as apache variable or as php.ini variable)

1.Docker Installation OK
Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

2.Docker Compose Installation OK
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

3. Shadowd Installation OK 
Cloned to /packaging/docker/compose
Setup, OK, System completely started
docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                                                     NAMES
e200550e3f1e        zecure/shadowd            "/docker-entrypoint.…"   24 hours ago        Up 24 hours         0.0.0.0:9115-                                                                 >9115/tcp   compose_shadowd_1
03b96b0f77c3        zecure/shadowd_ui         "/docker-entrypoint.…"   24 hours ago        Up 24 hours         0.0.0.0:8084-                                                                 >80/tcp     compose_web_1
a99ee4c8aecd        zecure/shadowd_database   "docker-entrypoint.s…"   24 hours ago        Up 24 hours         5432/tcp                                                                                  compose_db_1

4. User created
sudo ./shadowdctl exec web ./app/console swd:register --admin --name=admin

5. Profile created, exactly according to instructions.
Profile set in Learning mode

6. PHP Connector
- copied contents of src to /usr/share/shadowd/php, then -> granted rights to www-data
- copied connectors.ini to etc/shadowd, then -> granted rights to www-data
- auto prepend values are confirmed in phpinfo.php

7. Modified connectors.ini  according to instructions (see below) 
  
8. Checked UFW impact -> ufw configuration not altered; alternatively  UFW  totally disabled
 - no difference in functioning. turning firewall on/off does not make any diference
 
 RESULT:
 1. Web UI Accesible - can see the GUI, can add , remove users, access other functions (blacklist, whitelist, etc)
 2. Checking if modification in connectors ini are effective. Modification of variables in connectors.ini: a.) generate errors in webserver (e.g. 500 Internal Server Error , when specifying faulty SSL) , b.)  errors are traceable in Apache log (when specifying variable).
c.) service resumes when applying default configuration of connectirs.ini.
  3. Under the Analysis tab no info is shown. No request are shown, although  pages are being served by Apache.
 
 Conclusion:
- Web UI is accesible, but info from shadowd is not processed/receveid/displayed
- Shadowd seems to be working, since changes in ini, impact the functioning (error 500 Internal Server Error, etc)
- No impact of UFW firewall could be established.

I am stuck here. Any hint is really appreciated.

------------------------------- 


Connectors.ini
 
 [shadowd_php]
; Sets the profile id. Required.
profile=1

; Sets the key for the profile. Required.
key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

; Sets the address of the shadowd server.
; Default Value: 127.0.0.1
host=127.0.0.1

; Sets the port of the shadowd server.
; Default Value: 9115
port=9115

; Sets the path to the SSL certificate and enables SSL.
;ssl=


; If activated threats are not removed. This can be used to test new rules without
; making the web application unusable. It can be also used to turn Shadow Daemon
; into a high-interaction web honeypot.
; Possible Values:
;   0
;   1
; Default Value: 0
observe=0

; If activated status messages are send to the web server and saved in the log.
; Possible Values:
;   0
;   1
; Default Value: 0
debug=0


; If set the ignore list is used to ignore certain parameters and not send them to
; the shadowd server. It is good practise to not send passwords or other very
; sensitive information to the server.
ignore=0

; If activated raw post data is saved as user input. The raw data is hard to analyze,
; but can be a source for malicious input as well.
; Possible Values:
;   0
;   1
; Default Value: 0
raw_data=0

; Sets the source for the client ip. It is a key of $_SERVER. If you are using a
; reverse proxy or something similar forward the real client ip and reference it
; here, e.g., HTTP_X_FORWARDED_FOR.
; Default Value: REMOTE_ADDR
client_ip=REMOTE_ADDR

; Sets the source for the caller. It is a key of $_SERVER. If you are using web
; application with a front controller or something like that change it to PHP_SELF.
; Default Value: SCRIPT_FILENAME
caller=SCRIPT_FILENAME

; Sets the source for the resource identifier. It is a key of $_SERVER.
; Default Value: REQUEST_URI
resource=REQUEST_URI

**Comment by zit-hb** [comment] 2020-05-09 08:56
Do you have time for a Zoom session in the next days? Without having access to the system it is just too much guessing.

**Comment by rujanr** [comment] 2020-05-13 18:58
Hello, yes, anytime, it would be great. How to get in touch to convene the time? I am rujanr on gmail and radurujan on skype .

**Comment by zit-hb** [comment] 2020-05-19 20:32
You are from Romania, right? I am asking because of the timezone. If yes we are one hour apart. I would have time in the evening week-days in the next week or two.

**Comment by rujanr** [comment] 2020-05-20 17:29
Yes, you are right. The timing is good for me also.

**Comment by rujanr** [comment] 2020-05-21 19:37
Coming back with some details. I find in the apache error logs the following: 
shadowd: network error: connection refused
shadowd: processing error

**Comment by zit-hb** [comment] 2020-05-22 13:39
That would explain the problem and would have been my first guess if it wasn't for the `observe=0` in the connector config. This should result in a 500 error if the connection can not be established.

**Comment by rujanr** [comment] 2020-05-22 17:38
It is curious. No errors today. It might be that those errors were generated when making test changes with variables in the connectors.ini.

**Comment by rujanr** [comment] 2020-06-02 09:33
Hello, thnak you, but I only got to see the message now.  Maybe we could try another day, depending on your time?

**Comment by zit-hb** [comment] 2020-09-06 17:07
Kind of forgot it, sorry about that. Since it is so old I will close it for now, but please feel free to reopen if it is still an issue.

**Closed by zit-hb** 2020-09-06 17:07 UTC
